#!/bin/bash

# SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CUR_DIR=$(pwd)
CONTENT_DIR=/root/content
CONT_NAME=content-buildenv

if [[ $(podman ps --filter name=$CONT_NAME --format '{{.Names}}' | wc -l) -eq 0 ]]; then
  echo "Try to remove $CONT_NAME..."
  podman rm -f -t 1 -i $CONT_NAME
  echo "Starting $CONT_NAME..."
  # https://stackoverflow.com/a/36872226
  # Line DISPLAY ... to enable GUI, you may need to run `xhost` to grant access?
  podman run -td --rm --name $CONT_NAME \
      -e DISPLAY -v $XAUTHORITY:$XAUTHORITY:ro -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
      -p 127.0.0.1:8000-9000:8000-9000 \
      -v $CUR_DIR:$CONTENT_DIR \
      ghcr.io/huangjunwen/content-buildenv sleep infinity
fi

CMD="${@:-bash}"
echo "Will run <<$CMD>> in container <<$CONTENT_DIR>>"
exec podman exec -it $CONT_NAME $CMD


