#!/bin/bash

# SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CONT_NAME=content-buildenv

if [[ $(podman ps --filter name=$CONT_NAME --format '{{.Names}}' | wc -l) -eq 0 ]]; then

  echo "Try to remove $CONT_NAME..."
  podman rm -f -t 1 -i $CONT_NAME

  # Grant xhost access
  xhost +"local:podman@"

  # https://superuser.com/a/484330/135199
  HOMEDIR=$(getent passwd "$USER" | cut -d: -f6)

  # use `podman container diff content-buildenv` to check which directories have been changed
  CACHE_MOUNT="-v $CONT_NAME-luatex-cache:/var/lib/texmf/luatex-cache"
  if [[ "$HOMEDIR" != "/root" ]]; then
    # also mount root if im not root
    CACHE_MOUNT="$CACHE_MOUNT -v $CONT_NAME-root:/root"
  fi

  echo "Starting $CONT_NAME..."
  # https://stackoverflow.com/a/36872226
  podman run -td --rm --name $CONT_NAME \
      -v $HOMEDIR:$HOMEDIR $CACHE_MOUNT \
      -e DISPLAY -v $XAUTHORITY:$XAUTHORITY:ro -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
      -p 127.0.0.1:8000-9000:8000-9000 \
      -w $HOMEDIR \
      ghcr.io/huangjunwen/content-buildenv sleep infinity
fi

# XXX: CUR_DIR should exists on both host and container (e.g. inside home directory)
CUR_DIR=$(pwd)
CMD="${@:-bash}"
echo "Will run <<$CMD>> in container <<$CUR_DIR>>"
exec podman exec -w $CUR_DIR -it $CONT_NAME $CMD


